### ISSUE TITLE
LTeXSetLanguage command missing

### ISSUE THREAD

**Issue by ebiscaia** [icewind/ltex-client.nvim#2] opened 2023-03-19 07:19 UTC
Hi,

I just bumped into your plugin and I would like to mention that the command LTexSetLanguage is missing.
I am able to add words to the dictionary and set the location of it, but the plugin does not obey the language that is set in the ltex config (I tried to require your plugin before and after ltex and it always uses "en-US" instead of "en-AU" and turning "ltex-client.nvim" off makes ltex working with the Australian/British spellings.

Lemme know if I can help in any way to fix this issue.

Eddie

**Comment by icewind** [comment] 2023-03-20 04:17
Hi. So when you type `:LTeXSetLanguage` (please note, that case in your message is incorrect) the editor says the command is missing? As I understood you've set a startup language in your config different from `en-US`. Let me check this.

**Comment by icewind** [comment] 2023-03-20 07:48
Double checked the command and it seems to work fine. But I found an issue with preserving initial configuration. Updated the plugin. Please update it and let me know if your issue is resolved.

**Comment by ebiscaia** [comment] 2023-03-20 12:16
Hi, I just updated the plugin. Now I can save the words in the correct dictionary, but I am still having a problem with the command.

`E492: Not an editor command: LTeXSetLanguage` 

Thanks for the help

Edit: I tried removing everything, since it is a testing machine, with no changes.

**Comment by icewind** [comment] 2023-03-20 12:23
Ok. Thank you for the feedback. I'm binding this command only in specific files(that LTeX LS supports). I think there is another filetype I didn't covered. Can you please tell me what is the extension of your file and how nvim detects its type?

**Comment by icewind** [comment] 2023-03-20 13:50
I copied file types from `nvim lspconfig` repository. It seems to work fine now. Please update the plugin.

**Comment by ebiscaia** [comment] 2023-03-20 21:26
So, it seems it was a loading order issue. Before:

```
require("ltex-client").setup({                                                                                                                                     
    user_dictionaries_path = vim.fn.stdpath("config") .. "/spell/"                                                                                                 
})                                                                                                                                                                 
                                                                                                                                                                        
local lspconfig_status_ok, lspconfig = pcall(require, "lspconfig")                                                                                                    
if not lspconfig_status_ok then                                                                                                                                       
│   return                                                                                                                                                            
end                                                                                                                                                                   
                                                                                                                                                                        
local opts = {}                                                                                                                                                       
                                                                                                                                                                        
for _, server in pairs(servers) do                                                                                                                                    
│   opts = {                                                                                                                                                          
│   │   on_attach = require("eddie.lsp.handlers").on_attach,                                                                                                          
│   │   capabilities = require("eddie.lsp.handlers").capabilities,                                                                                                    
│   }                                                                                                                                                                 
│   │                                                                                                                                                                 
│   if server == "lua_ls" then                                                                                                                                        
│   │   local lua_opts = require("eddie.lsp.settings.lua_lsp")                                                                                                        
│   │   opts = vim.tbl_deep_extend("force", lua_opts, opts)                                                                                                           
│   end

│   if server == "ltex" then                                                                                                                                          
│   │   local ltex_opts = require("eddie.lsp.settings.ltex")                                                                                                          
│   │   opts = vim.tbl_deep_extend("force", ltex_opts, opts)                                                                                                          
│   end                                                                                                                                                               
│   │                                                                                                                                                                 
│   lspconfig[server].setup(opts)
```

And then I decided to move your require into the ltex opts file ("eddie.lsp.settings.ltex")
```
return {                                                                                                                                                              
│   settings = {                                                                                                                                                      
│   │   ltex = {                                                                                                                                                      
│   │   │   enabled = { "bibtex", "markdown", "latex", "text" },                                                                                                      
│   │   │   language = "en-AU",                                                                                                                                       
│   │   },                                                                                                                                                            
│   },                                                                                                                                                                
│   require("ltex-client").setup({                                                                                                                                    
│   │   user_dictionaries_path = vim.fn.stdpath("config") .. "/spell/"                                                                                                
│   }),                                                                                                                                                               
}
```

Then it started to work. It may be just the case of mentioning that in the README.

Thanks again for all the effort

Eddie

**Comment by icewind** [comment] 2023-03-21 04:56
Thank you for the feedback. In my configuration, I'm requiring it in a separate file but after lspconfig. Also tried to require it before and it works fine. I guess I need to investigate it. That is weird because this plugin adds handlers and doesn't require anything from ltex-ls config on the startup. 
Closing issue for now. If I find the root cause of the initialization issue, will update the readme

**Closed as completed by icewind** 2023-03-21 04:56 UTC
